# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=10)),
                ('inCurrency', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=20)),
                ('threshold', models.IntegerField()),
                ('timeframe', models.IntegerField()),
                ('currency_pair', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
